services:
  app:
    build:
      context: ./
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/data/project/resonite-FE/config.json:/headlessConfig/resonite-fe.json"
    environment:
      # Timezone required for Discord events to be put into the correct day category, if they have the day in the title.
      TZ: Canada/Eastern
      DCtoken: ${DCtoken}
      uptimeUrl: ${uptimeUrl}
      redisHost: redis
  redis:
    image: redis
    restart: always
    expose:
      - 6379